<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // ─── General ────────────────────────────────────────
            [
                'key' => 'site_name',
                'value' => 'Lgtech',
                'group' => 'general',
                'type' => 'text',
                'label' => 'Tên website',
                'is_public' => true,
            ],
            [
                'key' => 'site_tagline',
                'value' => 'Bán PC, Laptop & Linh kiện máy tính',
                'group' => 'general',
                'type' => 'text',
                'label' => 'Khẩu hiệu (Slogan)',
                'is_public' => true,
            ],
            [
                'key' => 'site_description',
                'value' => 'Chuyên cung cấp PC Gaming, Laptop, linh kiện máy tính chính hãng. Xây dựng cấu hình PC thông minh với công cụ kiểm tra tương thích.',
                'group' => 'general',
                'type' => 'textarea',
                'label' => 'Mô tả website',
                'is_public' => true,
            ],
            [
                'key' => 'site_logo',
                'value' => '',
                'group' => 'general',
                'type' => 'image',
                'label' => 'Logo website',
                'is_public' => true,
            ],
            [
                'key' => 'site_favicon',
                'value' => '',
                'group' => 'general',
                'type' => 'image',
                'label' => 'Favicon',
                'is_public' => true,
            ],
            [
                'key' => 'currency',
                'value' => 'VND',
                'group' => 'general',
                'type' => 'text',
                'label' => 'Đơn vị tiền tệ',
                'is_public' => true,
            ],
            [
                'key' => 'timezone',
                'value' => 'Asia/Ho_Chi_Minh',
                'group' => 'general',
                'type' => 'text',
                'label' => 'Múi giờ',
                'is_public' => false,
            ],

            // ─── Contact ────────────────────────────────────────
            [
                'key' => 'contact_phone',
                'value' => '1900 1234',
                'group' => 'contact',
                'type' => 'text',
                'label' => 'Số điện thoại',
                'is_public' => true,
            ],
            [
                'key' => 'contact_hotline',
                'value' => '0909 123 456',
                'group' => 'contact',
                'type' => 'text',
                'label' => 'Hotline',
                'is_public' => true,
            ],
            [
                'key' => 'contact_email',
                'value' => 'contact@pcshop.vn',
                'group' => 'contact',
                'type' => 'text',
                'label' => 'Email',
                'is_public' => true,
            ],
            [
                'key' => 'contact_address',
                'value' => '123 Nguyễn Văn Linh, Quận 7, TP.HCM',
                'group' => 'contact',
                'type' => 'textarea',
                'label' => 'Địa chỉ',
                'is_public' => true,
            ],
            [
                'key' => 'business_hours',
                'value' => 'T2 - CN: 8:00 - 21:00',
                'group' => 'contact',
                'type' => 'text',
                'label' => 'Giờ làm việc',
                'is_public' => true,
            ],
            [
                'key' => 'contact_map',
                'value' => '',
                'group' => 'contact',
                'type' => 'textarea',
                'label' => 'Google Maps embed URL',
                'is_public' => true,
            ],

            // ─── Social ─────────────────────────────────────────
            [
                'key' => 'social_facebook',
                'value' => 'https://facebook.com/pcshop',
                'group' => 'social',
                'type' => 'text',
                'label' => 'Facebook',
                'is_public' => true,
            ],
            [
                'key' => 'social_youtube',
                'value' => 'https://youtube.com/@pcshop',
                'group' => 'social',
                'type' => 'text',
                'label' => 'YouTube',
                'is_public' => true,
            ],
            [
                'key' => 'social_tiktok',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label' => 'TikTok',
                'is_public' => true,
            ],
            [
                'key' => 'social_zalo',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label' => 'Zalo OA',
                'is_public' => true,
            ],
            [
                'key' => 'social_instagram',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label' => 'Instagram',
                'is_public' => true,
            ],

            // ─── SEO ────────────────────────────────────────────
            [
                'key' => 'seo_title',
                'value' => 'Lgtech - Bán PC, Laptop & Linh kiện máy tính chính hãng',
                'group' => 'seo',
                'type' => 'text',
                'label' => 'Tiêu đề SEO mặc định',
                'is_public' => true,
            ],
            [
                'key' => 'seo_description',
                'value' => 'Lgtech - Chuyên cung cấp PC Gaming, Laptop, linh kiện máy tính chính hãng giá tốt. Build PC online, kiểm tra tương thích tự động.',
                'group' => 'seo',
                'type' => 'textarea',
                'label' => 'Mô tả SEO mặc định',
                'is_public' => true,
            ],
            [
                'key' => 'seo_keywords',
                'value' => 'pc gaming, laptop, linh kiện máy tính, build pc, mua pc, Lgtech',
                'group' => 'seo',
                'type' => 'text',
                'label' => 'Từ khóa SEO mặc định',
                'is_public' => true,
            ],
            [
                'key' => 'seo_og_image',
                'value' => '',
                'group' => 'seo',
                'type' => 'image',
                'label' => 'Ảnh chia sẻ mặc định (OG Image)',
                'is_public' => true,
            ],
            [
                'key' => 'google_analytics_id',
                'value' => '',
                'group' => 'seo',
                'type' => 'text',
                'label' => 'Google Analytics ID (UA/G-)',
                'is_public' => false,
            ],
            [
                'key' => 'google_tag_manager_id',
                'value' => '',
                'group' => 'seo',
                'type' => 'text',
                'label' => 'Google Tag Manager ID',
                'is_public' => false,
            ],
            [
                'key' => 'facebook_pixel_id',
                'value' => '',
                'group' => 'seo',
                'type' => 'text',
                'label' => 'Facebook Pixel ID',
                'is_public' => false,
            ],

            // ─── Homepage ───────────────────────────────────────
            [
                'key' => 'homepage_hero_autoplay',
                'value' => '1',
                'group' => 'homepage',
                'type' => 'boolean',
                'label' => 'Tự động chuyển banner trang chủ',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_hero_interval',
                'value' => '5000',
                'group' => 'homepage',
                'type' => 'number',
                'label' => 'Thời gian chuyển slide (mili giây)',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_hero_title',
                'value' => 'Giải pháp thiết bị điện cao cấp',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'Tiêu đề hero chính',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_hero_subtitle',
                'value' => 'Ổ cắm thông minh, thiết bị chiếu sáng & phụ kiện điện dân dụng chính hãng',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'Phụ đề hero',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_primary_cta_label',
                'value' => 'Xem sản phẩm',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'Nút CTA chính - Nhãn',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_primary_cta_url',
                'value' => '/san-pham',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'Nút CTA chính - URL',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_secondary_cta_label',
                'value' => 'Nhận tư vấn',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'Nút CTA phụ - Nhãn',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_secondary_cta_url',
                'value' => '/lien-he',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'Nút CTA phụ - URL',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_products_per_section',
                'value' => '8',
                'group' => 'homepage',
                'type' => 'number',
                'label' => 'Số sản phẩm mỗi mục trên trang chủ',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_featured_category_ids',
                'value' => '',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'ID danh mục nổi bật (phân cách dấu phẩy)',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_featured_category_slugs',
                'value' => '',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'Slug danh mục nổi bật (phân cách dấu phẩy, ưu tiên slug)',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_featured_product_ids',
                'value' => '',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'ID sản phẩm nổi bật pin trang chủ (CSV, theo thứ tự)',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_show_brands',
                'value' => '1',
                'group' => 'homepage',
                'type' => 'boolean',
                'label' => 'Hiện thanh thương hiệu trên trang chủ',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_show_posts',
                'value' => '1',
                'group' => 'homepage',
                'type' => 'boolean',
                'label' => 'Hiện bài viết nổi bật',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_brand_intro_title',
                'value' => 'Về LG Tech',
                'group' => 'homepage',
                'type' => 'text',
                'label' => 'Tiêu đề giới thiệu thương hiệu',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_brand_intro_content',
                'value' => 'LG Tech chuyên cung cấp thiết bị điện cao cấp, ổ cắm thông minh và phụ kiện điện dân dụng chính hãng với cam kết chất lượng hàng đầu.',
                'group' => 'homepage',
                'type' => 'textarea',
                'label' => 'Nội dung giới thiệu thương hiệu',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_usp_items',
                'value' => json_encode([
                    ['icon' => '🛡️', 'title' => 'Chính hãng 100%', 'desc' => 'Cam kết hàng chính hãng, có bảo hành'],
                    ['icon' => '🚚', 'title' => 'Giao hàng toàn quốc', 'desc' => 'Miễn phí ship đơn trên 500K'],
                    ['icon' => '💎', 'title' => 'Chất lượng cao cấp', 'desc' => 'Tiêu chuẩn an toàn quốc tế'],
                    ['icon' => '🔧', 'title' => 'Hỗ trợ kỹ thuật', 'desc' => 'Tư vấn lắp đặt miễn phí'],
                ]),
                'group' => 'homepage',
                'type' => 'textarea',
                'label' => 'Điểm nổi bật (USP) - JSON',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_target_customers',
                'value' => json_encode([
                    ['icon' => '🏠', 'title' => 'Nhà ở hiện đại', 'desc' => 'Giải pháp ổ cắm thanh ray, công tắc cho căn hộ, biệt thự'],
                    ['icon' => '🏨', 'title' => 'Khách sạn & Showroom', 'desc' => 'Thiết bị điện cao cấp, thẩm mỹ và an toàn'],
                    ['icon' => '🏢', 'title' => 'Văn phòng', 'desc' => 'Hệ thống điện linh hoạt, dễ mở rộng'],
                    ['icon' => '🤝', 'title' => 'Đại lý / Nhà thầu', 'desc' => 'Chính sách giá tốt, hỗ trợ kỹ thuật toàn diện'],
                ]),
                'group' => 'homepage',
                'type' => 'textarea',
                'label' => 'Đối tượng khách hàng (JSON)',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_case_studies',
                'value' => json_encode([]),
                'group' => 'homepage',
                'type' => 'textarea',
                'label' => 'Case study / dự án thực tế (JSON: [{title, location, image, description}])',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_testimonials',
                'value' => json_encode([]),
                'group' => 'homepage',
                'type' => 'textarea',
                'label' => 'Feedback khách hàng (JSON: [{name, role, content, avatar}])',
                'is_public' => true,
            ],
            [
                'key' => 'homepage_application_images',
                'value' => json_encode([]),
                'group' => 'homepage',
                'type' => 'textarea',
                'label' => 'Hình ảnh ứng dụng thực tế (JSON: [{image, caption}])',
                'is_public' => true,
            ],
            [
                'key' => 'google_map_embed',
                'value' => '',
                'group' => 'contact',
                'type' => 'textarea',
                'label' => 'Google Maps - URL nhúng hoặc <iframe>',
                'is_public' => true,
            ],

            // ─── Payment ────────────────────────────────────────
            [
                'key' => 'payment_bank_name',
                'value' => 'MB Bank',
                'group' => 'payment',
                'type' => 'text',
                'label' => 'Tên ngân hàng',
                'is_public' => true,
            ],
            [
                'key' => 'payment_bank_account',
                'value' => '0123456789',
                'group' => 'payment',
                'type' => 'text',
                'label' => 'Số tài khoản',
                'is_public' => true,
            ],
            [
                'key' => 'payment_bank_holder',
                'value' => 'CONG TY Lgtech',
                'group' => 'payment',
                'type' => 'text',
                'label' => 'Tên chủ tài khoản',
                'is_public' => true,
            ],
            [
                'key' => 'payment_cod_enabled',
                'value' => '1',
                'group' => 'payment',
                'type' => 'boolean',
                'label' => 'Cho phép thanh toán khi nhận hàng (COD)',
                'is_public' => true,
            ],

            // ─── Shipping ───────────────────────────────────────
            [
                'key' => 'shipping_free_threshold',
                'value' => '2000000',
                'group' => 'shipping',
                'type' => 'number',
                'label' => 'Miễn phí ship từ (VNĐ)',
                'is_public' => true,
            ],
            [
                'key' => 'shipping_default_fee',
                'value' => '30000',
                'group' => 'shipping',
                'type' => 'number',
                'label' => 'Phí ship mặc định (VNĐ)',
                'is_public' => true,
            ],
            [
                'key' => 'shipping_express_fee',
                'value' => '50000',
                'group' => 'shipping',
                'type' => 'number',
                'label' => 'Phí ship nhanh (VNĐ)',
                'is_public' => true,
            ],

            // ─── Email / SMTP ──────────────────────────────────
            [
                'key' => 'smtp_host',
                'value' => '',
                'group' => 'email',
                'type' => 'text',
                'label' => 'SMTP Host',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_port',
                'value' => '587',
                'group' => 'email',
                'type' => 'number',
                'label' => 'SMTP Port',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_username',
                'value' => '',
                'group' => 'email',
                'type' => 'text',
                'label' => 'SMTP Username',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_password',
                'value' => '',
                'group' => 'email',
                'type' => 'password',
                'label' => 'SMTP Password',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_encryption',
                'value' => 'tls',
                'group' => 'email',
                'type' => 'select',
                'label' => 'Mã hóa (Encryption)',
                'options' => json_encode(['choices' => ['tls', 'ssl', 'none']]),
                'is_public' => false,
            ],
            [
                'key' => 'smtp_from_address',
                'value' => '',
                'group' => 'email',
                'type' => 'text',
                'label' => 'Email người gửi (From Address)',
                'is_public' => false,
            ],
            [
                'key' => 'smtp_from_name',
                'value' => '',
                'group' => 'email',
                'type' => 'text',
                'label' => 'Tên người gửi (From Name)',
                'is_public' => false,
            ],
            [
                'key' => 'email_order_enabled',
                'value' => '1',
                'group' => 'email',
                'type' => 'boolean',
                'label' => 'Gửi email xác nhận đơn hàng',
                'is_public' => false,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('Seeded ' . count($settings) . ' settings');
    }
}
